kind: pipeline
name: default
type: docker

steps:
- name: docker  
  image: plugins/docker
  settings:
    registry: git.froth.zone
    username: sam
    password: 
      from_secret: password
    repo: git.froth.zone/sam/drone-deno-deploy
    tags: latest