kind: pipeline
name: default
type: docker

steps:
  - name: Build
    image: plugins/docker
    depends_on:
    - "clone"
    settings:
      repo: git.froth.zone/sam/drone-deno-deploy
      dry_run: true
    when:
      event:
      - pull_request

  - name: Build & Publish
    depends_on:
    - "clone"
    image: plugins/docker
    settings:
      registry: git.froth.zone
      username: sam
      password:
        from_secret: password
      repo: git.froth.zone/sam/drone-deno-deploy
      tags: latest
      when:
        branch:
        - master
        event:
          include:
          - push
          exclude:
          - pull_request
